import esbuild from "esbuild";
import process from "process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Polyfill for import.meta in CommonJS context
if (typeof import_meta === 'undefined') {
  var import_meta = {
    url: typeof __filename !== 'undefined' ? 'file://' + __filename : 'file:///obsidian-plugin'
  };
}
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "node:fs",
    "node:path",
    "node:url",
    "node:buffer",
    "node:stream",
    "node:crypto"
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/sgr-obisidian-agent/main.js",
  define: {
    global: "window",
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    "import.meta.url": "import_meta.url",
  },
  minify: prod,
});

// Ensure dist directory exists
if (!fs.existsSync("dist/sgr-obisidian-agent/")) {
  fs.mkdirSync("dist/sgr-obisidian-agent/", { recursive: true });
}

// Copy manifest.json and styles.css to dist
const copyFile = (src, dest) => {
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, dest);
    console.log(`Copied ${src} to ${dest}`);
  }
};

if (prod) {
  await context.rebuild();
  copyFile("manifest.json", "dist/sgr-obisidian-agent/manifest.json");
  copyFile("styles.css", "dist/sgr-obisidian-agent/styles.css");
  process.exit(0);
} else {
  // Copy files on initial build
  copyFile("manifest.json", "dist/sgr-obisidian-agent/manifest.json");
  copyFile("styles.css", "dist/sgr-obisidian-agent/styles.css");
  await context.watch();
}
