import esbuild from "esbuild";
import process from "process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Polyfill for import.meta in CommonJS context
if (typeof import_meta === 'undefined') {
  var import_meta = {
    url: typeof __filename !== 'undefined' ? 'file://' + __filename : 'file:///obsidian-plugin'
  };
}
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  loader: {
    ".ts": "ts",
    ".tsx": "tsx",
  },
  jsx: "transform",
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "node:fs",
    "node:path",
    "node:url",
    "node:buffer",
    "node:stream",
    "node:crypto",
    "path",
    "http",
    "https",
    "net",
    "tls",
    "stream",
    "util",
    "url",
    "buffer",
    "crypto",
    "fs",
    "os",
    "zlib",
    "querystring",
    "events",
    "child_process",
    "cluster",
    "dgram",
    "dns",
    "readline",
    "repl",
    "string_decoder",
    "timers",
    "tty",
    "v8",
    "vm",
    "worker_threads",
    "assert",
    "http-proxy-agent",
    "https-proxy-agent",
    "socks-proxy-agent"
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/sgr-obsidian-agent/main.js",
  define: {
    global: "window",
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    "import.meta.url": "import_meta.url",
  },
  minify: prod,
});

// Ensure dist directory exists
if (!fs.existsSync("dist/sgr-obsidian-agent/")) {
  fs.mkdirSync("dist/sgr-obsidian-agent/", { recursive: true });
}

// Copy manifest.json and styles.css to dist
const copyFile = (src, dest) => {
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, dest);
    console.log(`Copied ${src} to ${dest}`);
  }
};

// Copy files function
const copyFiles = () => {
  copyFile("manifest.json", "dist/sgr-obsidian-agent/manifest.json");
  copyFile("styles.css", "dist/sgr-obsidian-agent/styles.css");
};

if (prod) {
  await context.rebuild();
  copyFiles();
  process.exit(0);
} else {
  // Copy files on initial build
  copyFiles();
  
  // Watch for changes in manifest.json and styles.css
  const watchFiles = ["manifest.json", "styles.css"];
  const watchers = [];
  
  watchFiles.forEach((file) => {
    const watcher = fs.watch(file, (eventType) => {
      if (eventType === "change") {
        console.log(`File ${file} changed, copying...`);
        copyFiles();
      }
    });
    watchers.push(watcher);
  });
  
  // Watch for JS/TS changes
  await context.watch();
  
  // Cleanup watchers on exit
  process.on("SIGINT", () => {
    watchers.forEach((watcher) => watcher.close());
    process.exit(0);
  });
}
